version: '3'

services:
  video-streaming-service:
    image: video-streaming-service
    build:
      context: ./video-streaming-service
      dockerfile: Dockerfile
    container_name: video-streaming-service
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"